apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-rail-enclave-sa
  namespace: payment-rail-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/PaymentRailEnclaveExecutionRole
automountServiceAccountToken: false
